version: "3.7"

services:
  database:
    image: postgres
    container_name: database_mks
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=41568106
      - POSTGRES_DB=MKS
      - POSTGRES_HOST=locahost
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: mks-backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata:
    driver: local



